config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  root 'home#index'
  get 'home/countries'
 # resources :holidays, :collection => { :export => :get}
  resources :holidays do
    get 'get_holidays', on: :collection
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/holiday.rb
class Holiday < ApplicationRecord

end#class's end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  
  def index
    @q = Holiday.ransack(params[:q])
    @holidays = @q.result(distinct: true)
    @search = Holiday.search(params[:q])
    respond_to do |format|
      format.xlsx{
        response.headers['Content-Disposition'] = 'attachment; filename=holidays.xlsx'
      }
      format.html{ render :index }
    end
  end

  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: "Holiday was successfully created." }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: "Holiday was successfully updated." }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: "Holiday was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_holidays
    service = HolidayApiService.new.get_holidays
    redirect_to holidays_path, notice: "Holiday was successfully imported."
  end
  private
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def holiday_params
      params.require(:holiday).permit(:holiday_name, :date, :country)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def countries
    I18nData.countries.flatten
    @country_and_names_print = I18nData.countries.flatten
    @handle_comma_country = (@country_and_names_print).select {|i| (i).length < 3}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/holidays/_form.html.erb
 <%= form_with(model: holiday) do |form| %>
  <% if holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
        <% holiday.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :holiday_name %>
    <%= form.text_field :holiday_name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<h1>Editing Holiday</h1>

<%= render 'form', holiday: @holiday %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

app/views/holidays/index.html.erb
<p id="notice"><%= notice %></p>
<style>
h1{text-align: center;}
f.label{text-align: center;}
</style>

<h1>Holidays</h1>
<%= search_form_for @q do |f| %>

  <%= f.label :country %>:
  <%= f.search_field :country_cont, class: 'form-control' %>
  <%= f.label :holiday_name %>:
  <%= f.search_field :holiday_name_cont, class: 'form-control' %>
  <div style="line-height:150%;">
    <br>
  </div>
  <%= f.label :country %>  : 
  <%= f.select :country_cont, (I18nData.countries.flatten).select {|i| (i).length < 3}%>
    <br>
    <div class="col-md-12 text-center">
        <%= link_to "Clear", request.path, class: "btn btn-primary"%>
        <%= f.submit class: 'btn btn-primary'%>
    </div>
<% end %>
<%=
  link_to 'Download as Excel',
  holidays_path(format: :xlsx)
%>
<p>
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Holiday name</th>
      <th>Date</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.holiday_name %></td>
        <td><%= holiday.date %></td>
        <td><%= holiday.country %></td>
      </tr>
    <% end %>
  </tbody>
</table><br></br>

app/views/holidays/new.html.erb
<h1>New Holiday</h1>

<%= render 'form', holiday: @holiday %>

<%= link_to 'Back', holidays_path %>

app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

  <strong>Holiday name:</strong>
  <%= @holiday.holiday_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @holiday.date %>
</p>

<p>
  <strong>Country:</strong>
  <%= @holiday.country %>
</p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>

app/views/home/_countrylist.html.erb
<select id = "selected_country">
	<option value="AF">Afghanistan</option>
	<option value="AX">Åland Islands</option>
	<option value="AL">Albania</option>
	<option value="DZ">Algeria</option>
	<option value="AS">American Samoa</option>
	<option value="AD">Andorra</option>
	<option value="AO">Angola</option>
	<option value="AI">Anguilla</option>
	<option value="AQ">Antarctica</option>
	<option value="AG">Antigua and Barbuda</option>
	<option value="AR">Argentina</option>
	<option value="AM">Armenia</option>
	<option value="AW">Aruba</option>
	<option value="AU">Australia</option>
	<option value="AT">Austria</option>
	<option value="AZ">Azerbaijan</option>
	<option value="BS">Bahamas</option>
	<option value="BH">Bahrain</option>
	<option value="BD">Bangladesh</option>
	<option value="BB">Barbados</option>
	<option value="BY">Belarus</option>
	<option value="BE">Belgium</option>
	<option value="BZ">Belize</option>
	<option value="BJ">Benin</option>
	<option value="BM">Bermuda</option>
	<option value="BT">Bhutan</option>
	<option value="BO">Bolivia, Plurinational State of</option>
	<option value="BQ">Bonaire, Sint Eustatius and Saba</option>
	<option value="BA">Bosnia and Herzegovina</option>
	<option value="BW">Botswana</option>
	<option value="BV">Bouvet Island</option>
	<option value="BR">Brazil</option>
	<option value="IO">British Indian Ocean Territory</option>
	<option value="BN">Brunei Darussalam</option>
	<option value="BG">Bulgaria</option>
	<option value="BF">Burkina Faso</option>
	<option value="BI">Burundi</option>
	<option value="KH">Cambodia</option>
	<option value="CM">Cameroon</option>
	<option value="CA">Canada</option>
	<option value="CV">Cape Verde</option>
	<option value="KY">Cayman Islands</option>
	<option value="CF">Central African Republic</option>
	<option value="TD">Chad</option>
	<option value="CL">Chile</option>
	<option value="CN">China</option>
	<option value="CX">Christmas Island</option>
	<option value="CC">Cocos (Keeling) Islands</option>
	<option value="CO">Colombia</option>
	<option value="KM">Comoros</option>
	<option value="CG">Congo</option>
	<option value="CD">Congo, the Democratic Republic of the</option>
	<option value="CK">Cook Islands</option>
	<option value="CR">Costa Rica</option>
	<option value="CI">Côte d'Ivoire</option>
	<option value="HR">Croatia</option>
	<option value="CU">Cuba</option>
	<option value="CW">Curaçao</option>
	<option value="CY">Cyprus</option>
	<option value="CZ">Czech Republic</option>
	<option value="DK">Denmark</option>
	<option value="DJ">Djibouti</option>
	<option value="DM">Dominica</option>
	<option value="DO">Dominican Republic</option>
	<option value="EC">Ecuador</option>
	<option value="EG">Egypt</option>
	<option value="SV">El Salvador</option>
	<option value="GQ">Equatorial Guinea</option>
	<option value="ER">Eritrea</option>
	<option value="EE">Estonia</option>
	<option value="ET">Ethiopia</option>
	<option value="FK">Falkland Islands (Malvinas)</option>
	<option value="FO">Faroe Islands</option>
	<option value="FJ">Fiji</option>
	<option value="FI">Finland</option>
	<option value="FR">France</option>
	<option value="GF">French Guiana</option>
	<option value="PF">French Polynesia</option>
	<option value="TF">French Southern Territories</option>
	<option value="GA">Gabon</option>
	<option value="GM">Gambia</option>
	<option value="GE">Georgia</option>
	<option value="DE">Germany</option>
	<option value="GH">Ghana</option>
	<option value="GI">Gibraltar</option>
	<option value="GR">Greece</option>
	<option value="GL">Greenland</option>
	<option value="GD">Grenada</option>
	<option value="GP">Guadeloupe</option>
	<option value="GU">Guam</option>
	<option value="GT">Guatemala</option>
	<option value="GG">Guernsey</option>
	<option value="GN">Guinea</option>
	<option value="GW">Guinea-Bissau</option>
	<option value="GY">Guyana</option>
	<option value="HT">Haiti</option>
	<option value="HM">Heard Island and McDonald Islands</option>
	<option value="VA">Holy See (Vatican City State)</option>
	<option value="HN">Honduras</option>
	<option value="HK">Hong Kong</option>
	<option value="HU">Hungary</option>
	<option value="IS">Iceland</option>
	<option value="IN">India</option>
	<option value="ID">Indonesia</option>
	<option value="IR">Iran, Islamic Republic of</option>
	<option value="IQ">Iraq</option>
	<option value="IE">Ireland</option>
	<option value="IM">Isle of Man</option>
	<option value="IL">Israel</option>
	<option value="IT">Italy</option>
	<option value="JM">Jamaica</option>
	<option value="JP">Japan</option>
	<option value="JE">Jersey</option>
	<option value="JO">Jordan</option>
	<option value="KZ">Kazakhstan</option>
	<option value="KE">Kenya</option>
	<option value="KI">Kiribati</option>
	<option value="KP">Korea, Democratic People's Republic of</option>
	<option value="KR">Korea, Republic of</option>
	<option value="KW">Kuwait</option>
	<option value="KG">Kyrgyzstan</option>
	<option value="LA">Lao People's Democratic Republic</option>
	<option value="LV">Latvia</option>
	<option value="LB">Lebanon</option>
	<option value="LS">Lesotho</option>
	<option value="LR">Liberia</option>
	<option value="LY">Libya</option>
	<option value="LI">Liechtenstein</option>
	<option value="LT">Lithuania</option>
	<option value="LU">Luxembourg</option>
	<option value="MO">Macao</option>
	<option value="MK">Macedonia, the former Yugoslav Republic of</option>
	<option value="MG">Madagascar</option>
	<option value="MW">Malawi</option>
	<option value="MY">Malaysia</option>
	<option value="MV">Maldives</option>
	<option value="ML">Mali</option>
	<option value="MT">Malta</option>
	<option value="MH">Marshall Islands</option>
	<option value="MQ">Martinique</option>
	<option value="MR">Mauritania</option>
	<option value="MU">Mauritius</option>
	<option value="YT">Mayotte</option>
	<option value="MX">Mexico</option>
	<option value="FM">Micronesia, Federated States of</option>
	<option value="MD">Moldova, Republic of</option>
	<option value="MC">Monaco</option>
	<option value="MN">Mongolia</option>
	<option value="ME">Montenegro</option>
	<option value="MS">Montserrat</option>
	<option value="MA">Morocco</option>
	<option value="MZ">Mozambique</option>
	<option value="MM">Myanmar</option>
	<option value="NA">Namibia</option>
	<option value="NR">Nauru</option>
	<option value="NP">Nepal</option>
	<option value="NL">Netherlands</option>
	<option value="NC">New Caledonia</option>
	<option value="NZ">New Zealand</option>
	<option value="NI">Nicaragua</option>
	<option value="NE">Niger</option>
	<option value="NG">Nigeria</option>
	<option value="NU">Niue</option>
	<option value="NF">Norfolk Island</option>
	<option value="MP">Northern Mariana Islands</option>
	<option value="NO">Norway</option>
	<option value="OM">Oman</option>
	<option value="PK">Pakistan</option>
	<option value="PW">Palau</option>
	<option value="PS">Palestinian Territory, Occupied</option>
	<option value="PA">Panama</option>
	<option value="PG">Papua New Guinea</option>
	<option value="PY">Paraguay</option>
	<option value="PE">Peru</option>
	<option value="PH">Philippines</option>
	<option value="PN">Pitcairn</option>
	<option value="PL">Poland</option>
	<option value="PT">Portugal</option>
	<option value="PR">Puerto Rico</option>
	<option value="QA">Qatar</option>
	<option value="RE">Réunion</option>
	<option value="RO">Romania</option>
	<option value="RU">Russian Federation</option>
	<option value="RW">Rwanda</option>
	<option value="BL">Saint Barthélemy</option>
	<option value="SH">Saint Helena, Ascension and Tristan da Cunha</option>
	<option value="KN">Saint Kitts and Nevis</option>
	<option value="LC">Saint Lucia</option>
	<option value="MF">Saint Martin (French part)</option>
	<option value="PM">Saint Pierre and Miquelon</option>
	<option value="VC">Saint Vincent and the Grenadines</option>
	<option value="WS">Samoa</option>
	<option value="SM">San Marino</option>
	<option value="ST">Sao Tome and Principe</option>
	<option value="SA">Saudi Arabia</option>
	<option value="SN">Senegal</option>
	<option value="RS">Serbia</option>
	<option value="SC">Seychelles</option>
	<option value="SL">Sierra Leone</option>
	<option value="SG">Singapore</option>
	<option value="SX">Sint Maarten (Dutch part)</option>
	<option value="SK">Slovakia</option>
	<option value="SI">Slovenia</option>
	<option value="SB">Solomon Islands</option>
	<option value="SO">Somalia</option>
	<option value="ZA">South Africa</option>
	<option value="GS">South Georgia and the South Sandwich Islands</option>
	<option value="SS">South Sudan</option>
	<option value="ES">Spain</option>
	<option value="LK">Sri Lanka</option>
	<option value="SD">Sudan</option>
	<option value="SR">Suriname</option>
	<option value="SJ">Svalbard and Jan Mayen</option>
	<option value="SZ">Swaziland</option>
	<option value="SE">Sweden</option>
	<option value="CH">Switzerland</option>
	<option value="SY">Syrian Arab Republic</option>
	<option value="TW">Taiwan, Province of China</option>
	<option value="TJ">Tajikistan</option>
	<option value="TZ">Tanzania, United Republic of</option>
	<option value="TH">Thailand</option>
	<option value="TL">Timor-Leste</option>
	<option value="TG">Togo</option>
	<option value="TK">Tokelau</option>
	<option value="TO">Tonga</option>
	<option value="TT">Trinidad and Tobago</option>
	<option value="TN">Tunisia</option>
	<option value="TR">Turkey</option>
	<option value="TM">Turkmenistan</option>
	<option value="TC">Turks and Caicos Islands</option>
	<option value="TV">Tuvalu</option>
	<option value="UG">Uganda</option>
	<option value="UA">Ukraine</option>
	<option value="AE">United Arab Emirates</option>
	<option value="GB">United Kingdom</option>
	<option value="US">United States</option>
	<option value="UM">United States Minor Outlying Islands</option>
	<option value="UY">Uruguay</option>
	<option value="UZ">Uzbekistan</option>
	<option value="VU">Vanuatu</option>
	<option value="VE">Venezuela, Bolivarian Republic of</option>
	<option value="VN">Viet Nam</option>
	<option value="VG">Virgin Islands, British</option>
	<option value="VI">Virgin Islands, U.S.</option>
	<option value="WF">Wallis and Futuna</option>
	<option value="EH">Western Sahara</option>
	<option value="YE">Yemen</option>
	<option value="ZM">Zambia</option>
	<option value="ZW">Zimbabwe</option>
</select>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Holidays',root_path,class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      	<%=link_to "About me ", home_about_path, class: "navlink" %>
      	<%=link_to "Countries ", home_countries_path, class: "navlink" %>
      	<%=link_to "Holidays", holidays_path, class: "navlink" %>
        <%=link_to "Get Holidays", get_holidays_holidays_path, class: "navlink" %>
      </li>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<!DOCTYPE html>
<br><br/>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">

    <noscript>
      <style type="text/css">
        [data-aos] {
            opacity: 1 !important;
            transform: translate(0) scale(1) !important;
        }
      </style>
    </noscript>
  </head>
  <body id="top">
    
    <div class="page-content">
      <div>
<div class="profile-page">
  <div class="wrapper">
    <div class="page-header page-header-small" filter-color="green">
      <div class="page-header-image" data-parallax="true"></div>
      <div class="container">
        <div class="content-center">
          <div class="cc-profile-image"><a href="#"> <margin-left:30px> <%= image_tag "/assets/profile.jpg", size:"150x150"%></a></div>
          
          <div class="h2 title">Şafak Ferhat Kaya</div>
          <p class="category text-black">Electronic Engineer</p><a class="btn btn-primary smooth-scroll mr-2" href="#contact" data-aos="zoom-in" data-aos-anchor="data-aos-anchor">Hire Me</a>
        </div>
      </div>
      <div class="section">
        <div class="container">
          <div class="button-container"><a class="btn btn-default btn-round btn-lg btn-icon" href="https://github.com/safakferhatkaya" rel="tooltip" title="Follow me on Github"><i class="fa fa-github"></i></a><a class="btn btn-default btn-round btn-lg btn-icon" href="https://www.linkedin.com/in/safakferhatkaya/" rel="tooltip" title="Follow me on Linkedin"><i class="fa fa-linkedin"></i></a>
          	<a class="btn btn-default btn-round btn-lg btn-icon" href="https://open.spotify.com/user/safakferhatkaya?si=35d27dea05fe4d5f" rel="tooltip" title="Follow me on Spotify"><i class="fa fa-spotify"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section" id="about">
  <div class="container">
    <div class="card" data-aos="fade-up" data-aos-offset="10">
      <div class="row">
        <div class="col-lg-6 col-md-12">
          <div class="card-body">
            <div class="h4 mt-0 title">About</div>
            <p>Hi, I'm Şafak Ferhat.</p>
            <p>This is a template cv for I use to introduce myself.. although I am not very experienced in web development, at least I can manipulate the data I have and get used to a language/platform I have just learned and come up with a solution quickly (I hope you think so too). <a href="https://github.com/safakferhatkaya/rubyonrails" target="_blank">Github link of this project</a></p>
          </div>
        </div>
        <div class="col-lg-6 col-md-12">
          <div class="card-body">
            <div class="h4 mt-0 title">Basic Information</div>
            <div class="row">
              <div class="col-sm-4"><strong class="text-uppercase">Age:</strong></div>
              <div class="col-sm-8">22</div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Email:</strong></div>
              <div class="col-sm-8">safakferhatkaya@gmail.com</div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Phone:</strong></div>
              <div class="col-sm-8">+90 553 298 38 77</div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Address:</strong></div>
              <div class="col-sm-8">Baha Street, Pendik/Istanbul</div>
            </div>
            <div class="row mt-3">
              <div class="col-sm-4"><strong class="text-uppercase">Language:</strong></div>
              <div class="col-sm-8">Turkish, English</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="section" id="experience">
  <div class="container cc-experience">
    <div class="h4 text-center mb-4 title">Work Experience</div>

    <div class="card">
      <div class="row">
        <div class="col-md-3 bg-primary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500">
          <div class="card-body cc-experience-header">
            <p>July 2021 - October 2021</p>
            <div class="h5">Uzel Tech</div>
          </div>
        </div>
        <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
          <div class="card-body">
            <div class="h5">Summer Intern and Full Time Embedded Software Engineer</div>
            <p>Uzel Tech is a company that works on iot and environment monitoring
			systems for data centers and heat and humidity monitoring systems for
			pharmacies.
			<strong>Tasks: </strong>My intern project was a mobile charger that works with RF-ID
			to be used in restaurants and transfers the waiter's credit
			information to the web server. I was responsible for the
			hardware, software and boxing of this project and I
			completed it successfully.
			During my working period, I took part in many tasks such as
			preparing user manuals for products, shooting videos with
			the test software I made, presenting them to customers,
			purchasing, and making cost tables.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="row">
        <div class="col-md-3 bg-primary" data-aos="fade-right" data-aos-offset="50" data-aos-duration="500">
          <div class="card-body cc-experience-header">
            <p>July 2019</p>
            <div class="h5">Arcelik - LG</div>
          </div>
        </div>
        <div class="col-md-9" data-aos="fade-left" data-aos-offset="50" data-aos-duration="500">
          <div class="card-body">
            <div class="h5">Summer Intern</div>
            <p>Arçelik-Lg air conditioner company is a multinational company, but also
				the largest air conditioner production facility in the Turkey and doing a
				R&D internship here has been a great experience for me.
				<strong>Tasks: </strong><CR><LF>
				Research was conducted on voice controlled devices.
				Tests and solutions were made on the electromagnetic
				compatibility problem that prevents a device from working
				stably.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section" id="contact">
  <div class="cc-contact-information">
    <div class="container">
      <div class="cc-contact">
        <div class="row">
          <div class="col-md-9">
            <div class="card mb-0" data-aos="zoom-in">
              <div class="h4 text-center title">Contact Me</div>
              <div class="row">
                <div class="col-md-6">
                  <div class="card-body">
                    <form action="https://formspree.io/safakferhatkaya@gmail.com" method="POST">
                      <div class="p pb-3"><strong>Feel free to contact me </strong></div>
                      <div class="row mb-3">
                        <div class="col">
                          <div class="input-group"><span class="input-group-addon"><i class="fa fa-user-circle"></i></span>
                            <input class="form-control" type="text" name="name" placeholder="Name" required="required"/>
                          </div>
                        </div>
                      </div>
                      <div class="row mb-3">
                        <div class="col">
                          <div class="input-group"><span class="input-group-addon"><i class="fa fa-file-text"></i></span>
                            <input class="form-control" type="text" name="Subject" placeholder="Subject" required="required"/>
                          </div>
                        </div>
                      </div>
                      <div class="row mb-3">
                        <div class="col">
                          <div class="input-group"><span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                            <input class="form-control" type="email" name="_replyto" placeholder="E-mail" required="required"/>
                          </div>
                        </div>
                      </div>
                      <div class="row mb-3">
                        <div class="col">
                          <div class="form-group">
                            <textarea class="form-control" name="message" placeholder="Your Message" required="required"></textarea>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col">
                          <button class="btn btn-primary" type="submit">Send</button>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="card-body">
                    <p class="mb-0"><strong>Address </strong></p>
                    <p class="pb-2">Baha Street, Pendik/Istanbul</p>
                    <p class="mb-0"><strong>Phone</strong></p>
                    <p class="pb-2">+90 553 298 38 77</p>
                    <p class="mb-0"><strong>Email</strong></p>
                    <p>safakferhatkaya@gmail.com</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div></div>
    </div>

      <div class="text-center text-muted">
      	<p>Manipulated by Safak<p/>
        <p>&copy; Creative CV. All rights reserved.<br>Design - <a class="credit" href="https://templateflip.com" target="_blank">TemplateFlip</a></p>
      </div>
    </footer>
  </body>
</html>

app/views/home/countries.html.erb
<h1 style="font-family: Courier">Country List...</h1>
	<br></br>
		<p style="font-family : Courier"> Codes of Listed Countries: </p>
	<br></br>
		<%=	@handle_comma_country.map(&:inspect).join(', ') %>
	<br></br>

app/views/home/index.html.erb
<h1  style="font-family : Courier">Holiday Lists</h1>
	<body>
		<div>
			<p style="float: left;"><%= image_tag "/assets/holidays.PNG", size:"700x450"%>

			<p style="font-family : Courier"> <br><br/>
 				&emsp;Welcome to the application where countries and their holiday lists can be observed. </p>
				<br><br/>
			<p style="font-family : Courier">&emsp; Click <strong>
				<%=link_to "here", holidays_path, class: "navlink" %></strong> for holidays of countries.	
			<p style="font-family : Courier">&emsp; Click <strong>
				<%=link_to "here", home_about_path, class: "navlink" %></strong> to get to know me.
		</div>
	</body>